# Pipeline configuration for web scraper
name: "YouTube Scraper Pipeline"
description: "A pipeline for scraping YouTube"

# Use configuration from config.yaml
config: "config.yaml"

# Scraper mode: simple, selenium, scrapy, pyppeteer, playwright
scraper_mode: "playwright"

# URLs to scrape
urls:
  - "https://burst.shopify.com/"

# CSS selectors for data extraction
selectors:
  video_titles: "ytd-rich-item-renderer #video-title-link"
  channel_names: "ytd-rich-item-renderer #channel-name a"
  metadata: "ytd-rich-item-renderer #metadata-line span"
  video_urls: "ytd-rich-item-renderer #video-title-link[href]"

# Additional extraction options
extract_links: false
extract_images: false
extract_metadata: true

# Wait time configuration
wait_time: 10

# Post-processing configuration
post_processing:
  operations:
    - type: "deduplicate"
      columns: ["url"]
  
  export:
    format: "json"
    path: "processed_data"