# Pipeline configuration for web scraper
name: "Web Content Scraper Pipeline"
description: "A pipeline for scraping various types of web content (text, images, videos, YouTube)"

# Use configuration from config.yaml
config: "config.yaml"

# Scraper mode: simple, selenium, scrapy, pyppeteer, playwright
scraper_mode: "playwright"

# URLs to scrape (add your own URLs here)
urls:
  
  - "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  - "https://www.pexels.com/video/aerial-view-of-a-bridge-over-water-28550458/"


# Content extraction options
extract_text: true
extract_images: true
extract_videos: true
extract_youtube: true
extract_metadata: true
extract_links: true

# YouTube specific options
youtube:
  download_videos: true
  download_thumbnails: true
  preferred_resolution: "720p"
  download_audio_only: true  # Télécharger uniquement l'audio
  extract_audio: true  # Extraire l'audio des vidéos
  audio_format: "mp3"  # Format audio
  audio_quality: "192k"  # Qualité audio
  max_video_size: 1000  # MB

# Media download options
media:
  download_images: true
  download_videos: true
  download_audio: true
  max_file_size: 500  # MB

# Wait time configuration
wait_time: 10

# Error handling
error_handling:
  retry_on_failure: true
  max_retries: 3
  skip_ssl_verification: true

# Post-processing configuration
post_processing:
  operations:
    - type: "deduplicate"
      columns: ["url"]
    - type: "sort"
      column: "timestamp"
      ascending: false

  export:
    format: "json"
    path: "processed_data"

# Output organization
output:
  organize_by_domain: true
  organize_by_type: true
  create_summary_file: true